// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/event-types/:id/delete": {
            "delete": {
                "description": "Menghapus jenis event\n* Hanya bisa diakses oleh admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Type"
                ],
                "summary": "Delete Event Type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil menghapus event type",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal menghapus event type",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/event-types/:id/events": {
            "get": {
                "description": "Mendapatkan daftar event berdasarkan jenis event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Type"
                ],
                "summary": "Get Event By Event Type Id",
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan list event",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan list event",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/event-types/:id/update": {
            "put": {
                "description": "Memperbarui jenis event\n* Hanya bisa diakses oleh admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Type"
                ],
                "summary": "Update Event Type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Event Type Data",
                        "name": "event-type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EventType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil memperbarui event type",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal memperbarui event type",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/event-types/create": {
            "post": {
                "description": "Mendaftarkan jenis event\n* Hanya bisa diakses oleh admin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Type"
                ],
                "summary": "Create Event Type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Event Type Data",
                        "name": "event-type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EventType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil menambahkan event type",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal menambahkan event type",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/event-types/list": {
            "get": {
                "description": "Mendapatkan semua jenis event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event Type"
                ],
                "summary": "Get All Event Type",
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan event type",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan event type",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id": {
            "get": {
                "description": "Mendapatkan detail event berdasarkan id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Detail Event",
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan daftar event",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan daftar event",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id/delete": {
            "delete": {
                "description": "Menghapus event berdasarkan id\n* Hanya bisa diakses oleh admin atau organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Delete Event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil menghapus event",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal menghapus event",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id/reviews/:review_id/update": {
            "put": {
                "description": "Memperbarui data review untuk event\n* Hanya bisa diakses oleh user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review"
                ],
                "summary": "Update Review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Review Data",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Review"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil memperbarui review",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal memperbarui review",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id/reviews/create": {
            "post": {
                "description": "Menambahkan data review untuk event\n* Hanya bisa diakses oleh user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review"
                ],
                "summary": "Create Review",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Review Data",
                        "name": "review",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Review"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil menambahkan review",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal menambahkan review",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id/reviews/list": {
            "get": {
                "description": "Mendapatkan semua daftar review untuk event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Review"
                ],
                "summary": "List Review",
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan data review",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan data review",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id/tickets/:ticket_id/delete": {
            "put": {
                "description": "Menghapus data ticket untuk event\n* Hanya bisa diakses oleh admin atau organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Delete Ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil menghapus ticket",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal menghapus ticket",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id/tickets/:ticket_id/update": {
            "put": {
                "description": "Memperbarui data ticket untuk event\n* Hanya bisa diakses oleh admin atau organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Update Ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Ticket Data",
                        "name": "ticket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tikect"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil memperbarui ticket",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal memperbarui ticket",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id/tickets/create": {
            "post": {
                "description": "Menambahkan data ticket untuk event\n* Hanya bisa diakses oleh admin atau organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "Create Ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Ticket Data",
                        "name": "ticket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Tikect"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil menambahkan ticket",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal menambahkan ticket",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id/tickets/list": {
            "get": {
                "description": "Mendapatkan daftar ticket untuk event\n* Hanya bisa diakses oleh admin atau organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ticket"
                ],
                "summary": "List Ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan ticket",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan ticket",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/:event_id/update": {
            "put": {
                "description": "Memperbarui data event\n* Hanya bisa diakses oleh admin atau organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Update event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Event Data",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Event"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil memperbarui event",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal memperbarui event",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/create": {
            "post": {
                "description": "Menambahkan data event\n* Hanya bisa diakses oleh admin atau organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Create Event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Event Data",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Event"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil menambahkan event",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal menambahkan event",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/list": {
            "get": {
                "description": "Mendapatkan semua daftar event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "List Event",
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan daftar event",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/ResponseSuccessWithData"
                            }
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan daftar event",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/events/me": {
            "get": {
                "description": "Mendapatkan daftar event berdasarkan id user\n* Hanya bisa diakses oleh admin atau organizer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Detail Event By User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan daftar event",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan daftar event",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/orders/:order_id": {
            "get": {
                "description": "Mendapatkan order berdasarkan id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Detail Order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan detail order",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan detail order",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/orders/:order_id/cancel": {
            "put": {
                "description": "Membatalkan order\n* Hanya bisa diakses oleh user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Cancel Order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil membatalkan order",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal membatalkan order",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/orders/:order_id/pay": {
            "put": {
                "description": "Memperbarui status pembayaran order\n* Hanya bisa diakses oleh user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Pay Order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Order Data",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Order"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil membayar order",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal membayar order",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/orders/checkin/ticket": {
            "get": {
                "description": "Melakukan check-in pada order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Check In Order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order Id",
                        "name": "orderId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Order Item Id",
                        "name": "orderItemId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ticket Id",
                        "name": "ticketId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil melakukan check-in order",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal melakukan check-in order",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/orders/create": {
            "post": {
                "description": "Menambahkan data order\n* Hanya bisa diakses oleh user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "Create Order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Order Data",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/OrderCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil menambahkan order",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal menambahkan order",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/orders/list": {
            "put": {
                "description": "Mendapatkan daftar order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "List Order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan daftar order",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan daftar order",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/orders/user/:user_id/list": {
            "get": {
                "description": "Mendapatkan daftar order user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Order"
                ],
                "summary": "List Order User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan daftar order user",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan daftar order user",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/users/login": {
            "post": {
                "description": "Endpoint untuk login user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login User",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil login",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessToken"
                        }
                    },
                    "400": {
                        "description": "Gagal login",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil data user yang sedang login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mendapatkan user",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccessWithData"
                        }
                    },
                    "400": {
                        "description": "Gagal mendapatkan user",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        },
        "/api/users/register": {
            "post": {
                "description": "Endpoint untuk mendaftarkan user baru",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Register User",
                "parameters": [
                    {
                        "description": "User Data",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Users"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mendaftarkan user",
                        "schema": {
                            "$ref": "#/definitions/ResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "Gagal mendaftarkan user",
                        "schema": {
                            "$ref": "#/definitions/ResponseError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Event": {
            "description": "Fields untuk event",
            "type": "object",
            "required": [
                "event_date",
                "event_type_id",
                "location",
                "status",
                "title"
            ],
            "properties": {
                "created_at": {
                    "description": "waktu pembuatan event",
                    "type": "string"
                },
                "description": {
                    "description": "deskripsi event",
                    "type": "string"
                },
                "event_date": {
                    "description": "tanggal event",
                    "type": "string"
                },
                "event_type_id": {
                    "description": "id jenis event",
                    "type": "integer"
                },
                "id": {
                    "description": "Id dari event",
                    "type": "integer"
                },
                "location": {
                    "description": "lokasi event",
                    "type": "string"
                },
                "modified_at": {
                    "description": "waktu terakhir event diubah",
                    "type": "string"
                },
                "status": {
                    "description": "status event (open/closed)",
                    "type": "string",
                    "enum": [
                        "open",
                        "closed"
                    ]
                },
                "title": {
                    "description": "nama event",
                    "type": "string"
                },
                "user_id": {
                    "description": "Id user pembuat event",
                    "type": "integer"
                }
            }
        },
        "EventType": {
            "description": "Fields untuk jenis event",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "created_at": {
                    "description": "Waktu pembuatan jenis event",
                    "type": "string"
                },
                "id": {
                    "description": "Id dari jenis event",
                    "type": "integer"
                },
                "modified_at": {
                    "description": "Waktu terakhir jenis event diubah",
                    "type": "string"
                },
                "name": {
                    "description": "Nama jenis event",
                    "type": "string"
                }
            }
        },
        "LoginRequest": {
            "description": "Fields untuk request login",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "Email user",
                    "type": "string"
                },
                "password": {
                    "description": "Password user",
                    "type": "string"
                }
            }
        },
        "Order": {
            "description": "Fields untuk order",
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Waktu pembuatan order",
                    "type": "string"
                },
                "event_id": {
                    "description": "Id event yang dipesan",
                    "type": "integer"
                },
                "id": {
                    "description": "Id dari order",
                    "type": "integer"
                },
                "modified_at": {
                    "description": "Waktu terakhir order diubah",
                    "type": "string"
                },
                "order_item": {
                    "description": "Daftar item dalam order",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderItem"
                    }
                },
                "paid_at": {
                    "description": "Waktu pembayaran order",
                    "type": "string"
                },
                "payment_method": {
                    "description": "Metode pembayaran order (cash, transfer, etc)",
                    "type": "string"
                },
                "status": {
                    "description": "Status dari order (new, paid, complete, cancelled)",
                    "type": "string"
                },
                "total": {
                    "description": "Total harga dari order",
                    "type": "number"
                },
                "user_id": {
                    "description": "Id user yang membuat order",
                    "type": "integer"
                }
            }
        },
        "OrderCreate": {
            "description": "Fields untuk membuat order",
            "type": "object",
            "required": [
                "event_id",
                "ticket"
            ],
            "properties": {
                "event_id": {
                    "description": "Id event yang dipesan",
                    "type": "integer"
                },
                "ticket": {
                    "description": "Daftar tiket yang dipesan",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/OrderTicket"
                    }
                }
            }
        },
        "OrderItem": {
            "description": "Fields untuk item dalam order",
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Waktu pembuatan order item",
                    "type": "string"
                },
                "id": {
                    "description": "Id dari order item",
                    "type": "integer"
                },
                "is_check_in": {
                    "description": "Status check-in untuk order item (true jika sudah check-in)",
                    "type": "boolean"
                },
                "modified_at": {
                    "description": "Waktu terakhir order item diubah",
                    "type": "string"
                },
                "order_id": {
                    "description": "Id dari order yang berisi item ini",
                    "type": "integer"
                },
                "qr_code_url": {
                    "description": "Barcode unik untuk order item yang digunakan untuk check-in",
                    "type": "string"
                },
                "quantity": {
                    "description": "Jumlah tiket yang dipesan",
                    "type": "integer"
                },
                "ticket_type_id": {
                    "description": "Id dari tiket yang dipesan",
                    "type": "integer"
                }
            }
        },
        "OrderTicket": {
            "description": "Fields untuk tiket dalam order",
            "type": "object",
            "required": [
                "quantity",
                "ticket_type_id"
            ],
            "properties": {
                "quantity": {
                    "description": "Jumlah tiket yang dipesan",
                    "type": "integer",
                    "minimum": 1
                },
                "ticket_type_id": {
                    "description": "Id dari tiket yang dipesan",
                    "type": "integer"
                }
            }
        },
        "ResponseError": {
            "description": "menampilkan response error dengan pesan dan detail, bisa berupa error dari binding atau error lainnya jika detail tidak ada, maka akan diabaikan",
            "type": "object",
            "properties": {
                "detail": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "ResponseSuccess": {
            "description": "menampilkan response sukses hanya dengan pesan",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "ResponseSuccessToken": {
            "description": "menampilkan response sukses dengan token biasanya digunakan untuk otentikasi atau otorisasi",
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "ResponseSuccessWithData": {
            "description": "menampilkan response sukses dengan pesan dan data bisa berupa struct, slice, atau map jika data tidak ada, maka akan diabaikan",
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "Review": {
            "description": "Fields untuk review event",
            "type": "object",
            "required": [
                "rating"
            ],
            "properties": {
                "comment": {
                    "description": "Komentar dari review",
                    "type": "string"
                },
                "created_at": {
                    "description": "Waktu pembuatan review",
                    "type": "string"
                },
                "event_id": {
                    "description": "Id event yang direview",
                    "type": "integer"
                },
                "id": {
                    "description": "Id dari review",
                    "type": "integer"
                },
                "modified_at": {
                    "description": "Waktu terakhir review diubah",
                    "type": "string"
                },
                "rating": {
                    "description": "Rating dari review (1-5)",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1
                },
                "user_id": {
                    "description": "Id user yang membuat review",
                    "type": "integer"
                }
            }
        },
        "Tikect": {
            "description": "Fields untuk tiket event",
            "type": "object",
            "required": [
                "name",
                "price",
                "quota"
            ],
            "properties": {
                "created_at": {
                    "description": "Waktu pembuatan tiket",
                    "type": "string"
                },
                "event_id": {
                    "description": "Id event yang tiket ini miliki",
                    "type": "integer"
                },
                "id": {
                    "description": "Id dari tiket",
                    "type": "integer"
                },
                "modified_at": {
                    "description": "Waktu terakhir tiket diubah",
                    "type": "string"
                },
                "name": {
                    "description": "Nama dari tiket",
                    "type": "string"
                },
                "price": {
                    "description": "Harga dari tiket",
                    "type": "number"
                },
                "quota": {
                    "description": "Jumlah tiket yang tersedia",
                    "type": "integer"
                }
            }
        },
        "Users": {
            "description": "Fields untuk user",
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "created_at": {
                    "description": "Waktu pembuatan user",
                    "type": "string"
                },
                "email": {
                    "description": "Email user",
                    "type": "string"
                },
                "id": {
                    "description": "Id dari user",
                    "type": "integer"
                },
                "name": {
                    "description": "Nama user",
                    "type": "string"
                },
                "password": {
                    "description": "Password user",
                    "type": "string"
                },
                "role": {
                    "description": "Peran user (admin/user/organizer) jika kosong berarti perannya user",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
